run: mySigHandler sendsig division

mySigHandler: mySigHandler.c
	gcc mySigHandler.c -Wall -m32 -std=gnu99 -O0 -o mySigHandler

sendsig: sendsig.c
	gcc sendsig.c -Wall -m32 -std=gnu99 -O0 -o sendsig

division: division.c
	gcc division.c -Wall -m32 -std=gnu99 -O0 -o division